### ISSUE TITLE
Missing notification for received payments

### ISSUE THREAD

**Issue by st3vvv** [shocknet/wallet2#216]
I have recently been experimenting/testing out Shockwallet via the Bootstrap Node having installed the android APK and generally found things to be working .

I have, however noticed an issue with received payment notification not appearing for received payments when there is a small delay in the sending of the payment to the wallet.

For example, when receiving a payment to Shockwallet from my SN account, which is signed in on a separate device, and for which i therefore need to copy/paste the invoice, and transfer it manually to be able to fill the withdraw field on my SN account on the separate device (laptop) , i notice the notification for receiving the payment does not appear in Shockwallet, and the wallet does not update the wallet balance until it is closed/reopened.

Although the payment is received successfully, and the wallet balance does update correctly upon reopening the wallet, i also notice that the received payment does not appear in the transaction history.

Notifications and 'green arrow' received payments in the transaction history work fine when the delay is minimal - for example when sending from WOS on the same device - it seems to me to be some kind of timing issue when the delay in payment exceeds perhaps a minute or two.

(I have tested this using standard lightning and LNURL invoices with similar results - i haven't tried the On Chain option).

**Comment by shocknet-justin** [comment]
Thanks for the thorough description, have observed this too and it seems related to the mobile OS sleeping the nostr socket and not-reactivating it as expected when its back in focus... should have a workaround implemented soon
